version: '3.4'

services:
  app-ishop:
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - '/usr/srs/app/node_modules'
      - './:/usr/srs/app'
